# fly.toml app configuration file generated for brawlhalla on 2023-11-05T12:49:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brawlhalla"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
